### ISSUE TITLE
problem on loading the burp pro 

### ISSUE THREAD

**Issue by ongod2002** [SNGWN/Burp-Suite#11]
good day everyone 
please why done setting every required step its kind of fails loading please I need a guideline on how to solve this issue

this is the result it brings once failed to load:

┌──(kali㉿kali)-[~]
└─$ burp
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Your JRE appears to be version 11.0.10 from Debian
Burp has not been fully tested on this platform and you may experience problems.
    ____                      _____       _ __          __    ____            __         
   / __ )__  ___________     / ___/__  __(_) /____     / /   / __ \____ _____/ /__  _____
  / __  / / / / ___/ __ \    \__ \/ / / / / __/ _ \   / /   / / / / __ `/ __  / _ \/ ___/
 / /_/ / /_/ / /  / /_/ /   ___/ / /_/ / / /_/  __/  / /___/ /_/ / /_/ / /_/ /  __/ /    
/_____/\__,_/_/  / .___/   /____/\__,_/_/\__/\___/  /_____/\____/\__,_/\__,_/\___/_/     
                /_/                                                                      
Github:https://github.com/x-Ai/BurpSuiteLoader 商业使用请购买正版软件！
Could not start Burp: java.lang.ExceptionInInitializerError

**Comment by SNGWN** [comment]
Automating Activation process.
Update you soon
