### ISSUE TITLE
i had launched the keygen software and if i click run the portswigger logo appear and disapper 

### ISSUE THREAD

**Issue by prakadesh** [SNGWN/Burp-Suite#13]
Required JDK-18 is Installed

IdentifyingNumber : {31E89462-2587-5B56-8C7E-28A4D022A32B}
Name              : Java(TM) SE Development Kit 18.0.1.1 (64-bit)
Vendor            : Oracle Corporation
Version           : 18.0.1.1
Caption           : Java(TM) SE Development Kit 18.0.1.1 (64-bit)

Required JRE-8 is Installed

IdentifyingNumber : {26A24AE4-039D-4CA4-87B4-2F64180281F0}
Name              : Java 8 Update 281 (64-bit)
Vendor            : Oracle Corporation
Version           : 8.0.2810.9
Caption           : Java 8 Update 281 (64-bit)

Burp Suite Professional JAR file is available.
Checking its Integrity ....
File Looks fine. Lets proceed for Execution

Burp.bat file is created

Burp-Suite-Pro.vbs file is created.
Reloading Environment Variables ....

Starting Keygenerator ....

Starting Burp Suite Professional
Unrecognized option: --add-opens=java.desktop/javax.swing=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

system used in windows 11

**Comment by SNGWN** [comment]
Try executing command written In burp.bat file.
And look for the error
