### ISSUE TITLE
How can I Update to latest Version 

### ISSUE THREAD

**Issue by Astrosp** [SNGWN/Burp-Suite#23]
I need a latest feature that burp has release 
is their any way to do that

**Comment by Astrosp** [comment]
No worries ...! Found a way to update

**Comment by Astrosp** [comment]
owner already updated the script 
https://github.com/SNGWN/Burp-Suite/commit/25414e478294ccb81144a55f302654c6bc4e8241
Replace the existing Burp-Suite-Pro.jar file with downloaded jar file or rename that file and delete old file

**Comment by smith558** [comment]
> owner already updated the script [25414e4](https://github.com/SNGWN/Burp-Suite/commit/25414e478294ccb81144a55f302654c6bc4e8241) Replace the existing Burp-Suite-Pro.jar file with downloaded jar file or rename that file and delete old file

Yes, but that only works for the major version `2022.8.x`. Versions `2022.9.x` and higher do not work. They even changed the licence key encoding.

**Comment by Astrosp** [comment]
No,
I used this repo https://github.com/WankkoRee/BurpLoaderKeygenCnF

**Comment by Astrosp** [comment]
It's in Chinese, hard to understand but worked

**Comment by Astrosp** [comment]
> i have a updated loader if you need qoute reply

which repo
