### ISSUE TITLE
Does not work with 2022.9.3

### ISSUE THREAD

**Issue by frakman1** [SNGWN/Burp-Suite#26]
When using the latest .jar file, the activation key was rejected.
URL used:
https://portswigger-cdn.net/burp/releases/download?product=pro&version=2022.9.3&type=jar

**Comment by nu11secur1ty** [comment]
:D There is no official loader for 2022.9.x ;)

**Comment by nu11secur1ty** [comment]
Now you can load the new versions. search in GitHub (BurpSuiteLoader.jar), and download it ;)
Lin and Win
```
cd /env/blabala-burp-env/
java -noverify -javaagent:BurpSuiteLoader.jar -jar .\burpsuite_pro_v2022.9.5.jar
```
exit 0;

**Comment by smith558** [comment]
> Ok thanks. Will close issue then.

@frakman1  Have you figured out how to activate versions `2022.9.x`?

**Comment by nu11secur1ty** [comment]
Yes of course, but don't be mad at me You must buy a certificate ;)

**Comment by nu11secur1ty** [comment]
> > Yes, when you buy a certificate - key, don't be mad at me! ;) https://portswigger.net/buy/pro
> 
> With a price tag of 500 USD not really an option for a student. Maybe in the future tho. :)

You cam use the community edition, this will be so much better for learning how to detect a vulnerability manually and etc...

**Comment by Saitama0x0** [comment]
if you need a updated loader qoute replay this

**Comment by Saitama0x0** [comment]
i have a updated loader
