### ISSUE TITLE
The supplied license key was not recognized

### ISSUE THREAD

**Issue by Nishantbhagat57** [SNGWN/Burp-Suite#29]
The supplied license key was not recognized

![Screenshot 2022-11-04 123442](https://user-images.githubusercontent.com/64642374/199912255-e0a0d8c7-185b-48cf-a2a5-2a8438eaa2fb.png)

**Comment by Nishantbhagat57** [comment]
Okay, I found a way, Install with old version, then update to latest one.

**Comment by smith558** [comment]
> Okay, I found a way, Install with old version, then update to latest one.

Could you provide steps maybe?
