### ISSUE TITLE
Update burpsuite?

### ISSUE THREAD

**Issue by a6thmfsin** [SNGWN/Burp-Suite#30]
Any idea which versions you can update to?  I tried the latest version but got java.lang.nullpointerexception in terminal i downloaded the shell script from portswigger and moved the .jar file from that folder to where im launching this one from. Which version is this anyways?

**Comment by CharonXXI** [comment]
Same problem :/

**Comment by yeucodonvn** [comment]
me too

**Comment by saheredelgadom** [comment]
The latest version can no longer be used, it does not recognize the license.

It only works up to version 2022.8.5

**Comment by Saitama0x0** [comment]
yes i am having the same problem cant update after 2022.8.5

**Comment by whitefight18** [comment]
> The latest version can no longer be used, it does not recognize the license.
> 
> It only works up to version 2022.8.5

Yupp, he's right, on after 2022.9.x they introduced a new license check mechanism :'), so till now 2022.8.5 is the last one upto which u can use bypass

**Comment by Saitama0x0** [comment]
i have a new bypass and its works in all version including 22.12.5.anyone need dm me on [twitter.com/saitama0x](https://twitter.com/saitama0x)

**Comment by saheredelgadom** [comment]
@Saitama0x0 Could you please tell me how?, where? This is the technique, software that performs the bypass to activate BurpSuite in more current versions, you passed it was a twitter url, which is your own account but I did not find anything related to burpSuite PRO.

**Comment by Saitama0x0** [comment]
this is the of that file https://usersdrive.com/mcnqj2j5nzaq.html download it and extract it.You will find the burp 22.12.4 you can choose any ver of burp . if you use the 12.5 the change the version name in the step1.bat file and it will work fine. also read doc

**Comment by saheredelgadom** [comment]
Thanks @Saitama0x0 , is this version for linux???

**Comment by Saitama0x0** [comment]
Linux Windows both.You have to configure it for linux thats all

**Comment by Saitama0x0** [comment]
> Thanks @Saitama0x0 , is this version for linux???

♥️♥️

**Comment by saheredelgadom** [comment]
@Saitama0x0  The rar file doesn't have any step1.bat file, which would basically be bash for windows, it won't work on linux at all unless the code is changed, but that's the least of the problems, the main one is that there is no step1 file .bat.

**Comment by Pyloris** [comment]
@Saitama0x0 It does not accept the license. I tried on both linux & windows.

**Comment by Pyloris** [comment]
@Saitama0x0 no bro it does actually work. fixed it. I have conf files out of folders so it was not working correctly. Now it works.

**Comment by Saitama0x0** [comment]
> @Saitama0x0 no bro it does actually work. fixed it. I have conf files out of folders so it was not working correctly. Now it works.

hmmm thats right

**Comment by BustedElbows** [comment]
> > @Saitama0x0 no bro it does actually work. fixed it. I have conf files out of folders so it was not working correctly. Now it works.
> 
> hmmm thats right

I've got a question if that's possible. How do I config it for Linux? Considering everything in the file you posted is .bat. And do I need to have a version of Burp Pro and then utilize the reset license? Sorry for the questions, I'm not quite familiar with the concept of keygen and cracking burp.

**Comment by Pyloris** [comment]
@BustedElbows for linux just change the .bat to .sh and remove @echo off from the .bat file

**Comment by BustedElbows** [comment]
> @BustedElbows for linux just change the .bat to .sh and remove @echo off from the .bat file

It's that easy? I tried something from that sort but I remember have issues with the path.
