### ISSUE TITLE
license key error

### ISSUE THREAD

**Issue by Vibhav-XLR8** [SNGWN/Burp-Suite#31]
the license key is not working showing this while copy-pasting => the supplied license key was not recognised please try re-entering your license key

**Comment by commixan** [comment]
It didnt work on my new install of kali linux but it dit work on my windows 11

**Comment by commixan** [comment]
want to say thanks. great job brother

**Comment by 108-maheshwara** [comment]
> the license key is not working showing this while copy-pasting => the supplied license key was not recognised please try re-entering your license key

Did you try changing the name?

**Comment by Vibhav-XLR8** [comment]
> > the license key is not working showing this while copy-pasting => the supplied license key was not recognised please try re-entering your license key
> 
> Did you try changing the name?

yes i did

**Comment by Supraja9726** [comment]
It is the same issue for me as well. Are there any solutions yet? 
Note: I am using the old README.md file - I want this on my ubuntu machine

**Comment by fjernsynet** [comment]
Same issue, licence not working. The loading command in the keygen is also java -Xbootclasspath/p:keygen.jar -jar burpsuite_jar_not_found.jar

**Comment by whitefight18** [comment]
Here, so i found a fix /or say bypass. You need to create a json config file under `C:\Users\UR_USERNAME\AppData\Roaming\BurpSuite`.

>BEFORE even running the burp_pro.jar or keygen or loader.jar files -
Create a file with notepad or an IDE, containing the below code in it and name it - `UserConfigPro.json` and keep it in the above path/directory.
>Run keygen.jar and the neccesary steps to run the burp_pro (with the .vbs script, if its there)
>Follow the rest steps - [https://github.com/SNGWN/Burp-Suite#burp-suite-pro-activation-steps](from here).

`{
    "user_options":{
        "connections":{
            "platform_authentication":{
                "credentials":[],
                "do_platform_authentication":true,
                "prompt_on_authentication_failure":false
            },
            "socks_proxy":{
                "dns_over_socks":false,
                "host":"",
                "password":"",
                "port":0,
                "use_proxy":false,
                "username":""
            },
            "upstream_proxy":{
                "servers":[]
            }
        },
        "display":{
            "character_sets":{
                "mode":"recognize_automatically"
            },
            "html_rendering":{
                "allow_http_requests":true
            },
            "http_message_display":{
                "font_name":"Lucida Console",
                "font_size":15,
                "font_smoothing":true,
                "highlight_requests":true,
                "highlight_responses":true,
                "pretty_print_by_default":true
            },
            "user_interface":{
                "font_size":13,
                "look_and_feel":"Dark"
            }
        },
        "extender":{
            "extensions":[],
            "java":{
                "folder_for_loading_library_jar_files":""
            },
            "python":{
                "folder_for_loading_modules":"",
                "location_of_jython_standalone_jar_file":""
            },
            "ruby":{
                "location_of_jruby_jar_file":""
            },
            "settings":{
                "automatically_reload_extensions_on_startup":true,
                "automatically_update_bapps_on_startup":true
            }
        },
        "intruder":{
            "tab_bar_layout":"wrapped"
        },
        "misc":{
            "api":{
                "address":"",
                "enabled":false,
                "insecure_mode":false,
                "keys":[],
                "listen_mode":"loopback_only",
                "port":1337
            },
            "automatic_project_backup":{
                "delete_on_shutdown":true,
                "enabled":true,
                "in_scope_only":false,
                "interval":30,
                "show_progress":true
            },
            "embedded_browser":{
                "allow_saving_browser_settings":true
            },
            "enable_proxy_interception_at_startup":"never",
            "exceptions_log_directory":"",
            "hotkeys":[
                {
                    "action":"send_to_repeater",
                    "hotkey":"Ctrl+R"
                },
                {
                    "action":"send_to_intruder",
                    "hotkey":"Ctrl+I"
                },
                {
                    "action":"forward_intercepted_proxy_message",
                    "hotkey":"Ctrl+F"
                },
                {
                    "action":"toggle_proxy_interception",
                    "hotkey":"Ctrl+T"
                },
                {
                    "action":"issue_repeater_request",
                    "hotkey":"Ctrl+Space"
                },
                {
                    "action":"switch_to_dashboard",
                    "hotkey":"Ctrl+Shift+D"
                },
                {
                    "action":"switch_to_target",
                    "hotkey":"Ctrl+Shift+T"
                },
                {
                    "action":"switch_to_proxy",
                    "hotkey":"Ctrl+Shift+P"
                },
                {
                    "action":"switch_to_intruder",
                    "hotkey":"Ctrl+Shift+I"
                },
                {
                    "action":"switch_to_repeater",
                    "hotkey":"Ctrl+Shift+R"
                },
                {
                    "action":"switch_to_logger",
                    "hotkey":"Ctrl+Shift+L"
                },
                {
                    "action":"switch_to_project_options",
                    "hotkey":"Ctrl+Shift+O"
                },
                {
                    "action":"go_to_previous_tab",
                    "hotkey":"Ctrl+Minus"
                },
                {
                    "action":"go_to_next_tab",
                    "hotkey":"Ctrl+Equals"
                },
                {
                    "action":"editor_cut",
                    "hotkey":"Ctrl+X"
                },
                {
                    "action":"editor_copy",
                    "hotkey":"Ctrl+C"
                },
                {
                    "action":"editor_paste",
                    "hotkey":"Ctrl+V"
                },
                {
                    "action":"editor_undo",
                    "hotkey":"Ctrl+Z"
                },
                {
                    "action":"editor_redo",
                    "hotkey":"Ctrl+Y"
                },
                {
                    "action":"editor_select_all",
                    "hotkey":"Ctrl+A"
                },
                {
                    "action":"editor_search",
                    "hotkey":"Ctrl+S"
                },
                {
                    "action":"editor_go_to_previous_search_match",
                    "hotkey":"Ctrl+Comma"
                },
                {
                    "action":"editor_go_to_next_search_match",
                    "hotkey":"Ctrl+Period"
                },
                {
                    "action":"editor_url_decode",
                    "hotkey":"Ctrl+Shift+U"
                },
                {
                    "action":"editor_url_encode_key_characters",
                    "hotkey":"Ctrl+U"
                },
                {
                    "action":"editor_html_decode",
                    "hotkey":"Ctrl+Shift+H"
                },
                {
                    "action":"editor_html_encode_key_characters",
                    "hotkey":"Ctrl+H"
                },
                {
                    "action":"editor_base64_decode",
                    "hotkey":"Ctrl+Shift+B"
                },
                {
                    "action":"editor_base64_encode",
                    "hotkey":"Ctrl+B"
                },
                {
                    "action":"editor_backspace_word",
                    "hotkey":"Ctrl+Backspace"
                },
                {
                    "action":"editor_delete_word",
                    "hotkey":"Ctrl+Delete"
                },
                {
                    "action":"editor_delete_line",
                    "hotkey":"Ctrl+D"
                },
                {
                    "action":"editor_go_to_previous_word",
                    "hotkey":"Ctrl+Left"
                },
                {
                    "action":"editor_go_to_previous_word_extend_selection",
                    "hotkey":"Ctrl+Shift+Left"
                },
                {
                    "action":"editor_go_to_next_word",
                    "hotkey":"Ctrl+Right"
                },
                {
                    "action":"editor_go_to_next_word_extend_selection",
                    "hotkey":"Ctrl+Shift+Right"
                },
                {
                    "action":"editor_go_to_previous_paragraph",
                    "hotkey":"Ctrl+Up"
                },
                {
                    "action":"editor_go_to_previous_paragraph_extend_selection",
                    "hotkey":"Ctrl+Shift+Up"
                },
                {
                    "action":"editor_go_to_next_paragraph",
                    "hotkey":"Ctrl+Down"
                },
                {
                    "action":"editor_go_to_next_paragraph_extend_selection",
                    "hotkey":"Ctrl+Shift+Down"
                },
                {
                    "action":"editor_go_to_start_of_document",
                    "hotkey":"Ctrl+Home"
                },
                {
                    "action":"editor_go_to_start_of_document_extend_selection",
                    "hotkey":"Ctrl+Shift+Home"
                },
                {
                    "action":"editor_go_to_end_of_document",
                    "hotkey":"Ctrl+End"
                },
                {
                    "action":"editor_go_to_end_of_document_extend_selection",
                    "hotkey":"Ctrl+Shift+End"
                }
            ],
            "http_message_search":{
                "autoscroll_to_match_by_default":false,
                "case_sensitive_by_default":false,
                "regex_by_default":false
            },
            "inspector_display_mode":"auto-expand",
            "inspector_position":"right",
            "inspector_widget_configurations":[
                {
                    "open_by_default":false,
                    "show":true,
                    "type":"request_attributes",
                    "wrap_text":false
                },
                {
                    "open_by_default":false,
                    "show":true,
                    "type":"request_query_parameters",
                    "wrap_text":false
                },
                {
                    "open_by_default":false,
                    "show":true,
                    "type":"request_body_parameters",
                    "wrap_text":false
                },
                {
                    "open_by_default":false,
                    "show":true,
                    "type":"request_cookies",
                    "wrap_text":false
                },
                {
                    "open_by_default":false,
                    "show":true,
                    "type":"request_headers",
                    "wrap_text":false
                },
                {
                    "open_by_default":false,
                    "show":true,
                    "type":"response_headers",
                    "wrap_text":false
                }
            ],
            "log_exceptions_to_local_directory":false,
            "message_editor_request_configurations":[
                {
                    "show":true,
                    "type":"pretty"
                },
                {
                    "show":true,
                    "type":"raw"
                },
                {
                    "show":true,
                    "type":"hex"
                },
                {
                    "show":false,
                    "type":"headers",
                    "wrap_text":false
                },
                {
                    "show":false,
                    "type":"query_parameters",
                    "wrap_text":false
                },
                {
                    "show":false,
                    "type":"body_parameters",
                    "wrap_text":false
                },
                {
                    "show":false,
                    "type":"cookies",
                    "wrap_text":false
                },
                {
                    "show":false,
                    "type":"attributes",
                    "wrap_text":false
                }
            ],
            "message_editor_response_configurations":[
                {
                    "show":true,
                    "type":"pretty"
                },
                {
                    "show":true,
                    "type":"raw"
                },
                {
                    "show":true,
                    "type":"hex"
                },
                {
                    "show":true,
                    "type":"render"
                },
                {
                    "show":false,
                    "type":"headers",
                    "wrap_text":false
                }
            ],
            "out_of_scope_history_logging_action":"disable",
            "pause_tasks_at_startup_default":true,
            "show_learn_tab":true,
            "submit_anonymous_feedback":false,
            "temporary_files_location":""
        },
        "proxy":{
            "http_history":{
                "sort_column":"#",
                "sort_order":"ascending"
            },
            "websockets_history":{
                "sort_column":"#",
                "sort_order":"ascending"
            }
        },
        "repeater":{
            "tab_bar_layout":"wrapped"
        },
        "ssl":{
            "client_certificates":{
                "certificates":[]
            },
            "negotiation":{
                "disable_sni_extension":false,
                "enable_blocked_algorithms":true
            }
        },
        "target":{
            "view":"left_right_split"
        }
    }
}`

**Comment by whitefight18** [comment]
@SNGWN I guess u can close this issue thread   : D

**Comment by fjernsynet** [comment]
The supplied license key still couldn't be recognized.

**Comment by fjernsynet** [comment]
To add: It won't let me get to manual activation.

**Comment by whitefight18** [comment]
> To add: It won't let me get to manual activation.

Clear temp files from `%TEMP%` in run , close existing burp_pro.jar(s), remove previous UserConfigPro.json files from AppData\Roaming\Burpsuite, paste the above settings/code in a file and make it the UserConfigPro.json and keep it under same location/directory & lastly use 2022.8.5 Burp_pro.jar.

**Comment by Hafidz8992** [comment]
what do you mean the spesific temp file? or .TMP file?

**Comment by whitefight18** [comment]
![image](https://user-images.githubusercontent.com/62407496/209775973-0a37ffcb-975d-4cda-8a6b-498834fd1586.png)

I mean the resultant directory of this run command : )
i.e. ur temp files at `C:\Users\ur_username\AppData\Local\Temp`

**Comment by crossdefalt** [comment]
Enter license key error in kali linux
