### ISSUE TITLE
Cannot Update to the latest version

### ISSUE THREAD

**Issue by Menatic007** [SNGWN/Burp-Suite#32]
Hey can you please fix the key for us to update to the latest version, thanks

**Comment by Code-saif** [comment]
I can't upgrade to the latest version when replace the Burp-Suite-Pro.jar file with latest version it is asking me license key after replacing the latest verion file. can you solve this problem?

**Comment by Saitama0x0** [comment]
You cant.Because after 22.8.5 they have updated their licence mechanism.But i have a bypass anyone need?

**Comment by Saitama0x0** [comment]
You can use the latest 22.12.5 or larer

**Comment by Code-saif** [comment]
> You cant.Because after 22.8.5 they have updated their licence mechanism.But i have a bypass anyone need?

i would really appreciate how can i get it?

**Comment by Saitama0x0** [comment]
this is the file https://usersdrive.com/mcnqj2j5nzaq.html download it and extract it.You will find the burp 22.12.4 you can choose any ver of burp . if you use the 12.5 the change the version name in the step1.bat file and it will work fine. also read doc

**Comment by WhatTheFuckIsOatmeal** [comment]
> this is the file https://usersdrive.com/mcnqj2j5nzaq.html download it and extract it.You will find the burp 22.12.4 you can choose any ver of burp . if you use the 12.5 the change the version name in the step1.bat file and it will work fine. also read doc

I'm interested.. how did you figure this out? I'm just starting the ropes of reverse engineering so very interested!

**Comment by deepansh39** [comment]
hello bro its working good 
https://usersdrive.com/mcnqj2j5nzaq.html

**Comment by Jailbiee** [comment]
Why

**Comment by Jailbiee** [comment]
Then can you please give the Link to the new license key.

**Comment by deepansh39** [comment]
ohhhh i seeee actually i thought dont need key to update because my burp hang multiple time specially in repeater time

**Comment by Jailbiee** [comment]
Ok, thanks.

**Comment by Jailbiee** [comment]
But please can I learn from u because I'm intermediate user of burpsuite
and I get confused with it's extensions and others can u please help me out
.

**Comment by deepansh39** [comment]
ok if you stuck any where i help you migh be i am not gonna reply you here but text me there @deepanshuladwal twitter

**Comment by Saitama0x0** [comment]
> > this is the file https://usersdrive.com/mcnqj2j5nzaq.html download it and extract it.You will find the burp 22.12.4 you can choose any ver of burp . if you use the 12.5 the change the version name in the step1.bat file and it will work fine. also read doc
> 
> I'm interested.. how did you figure this out? I'm just starting the ropes of reverse engineering so very interested!

do you know reverse engineering ?
