### ISSUE TITLE
the supplied license key was not recognized.

### ISSUE THREAD

**Issue by testingssh4** [SNGWN/Burp-Suite#48]
After Entering License key, I am getting this error "the supplied license key was not recognized" and not able to process further. Installing it in Windows10. Please help why I am getting this error and how to resolve this.
![image](https://user-images.githubusercontent.com/131162518/235414407-66d5f718-57a6-4840-9bcc-ae496d40d433.png)

**Comment by Snavens** [comment]
same issue here 😿

**Comment by Saitama0x0** [comment]
you need new loader to use the latest versions of burp

**Comment by testingssh4** [comment]
How do you get that new loader?
