### ISSUE TITLE
Error in step 6.1

### ISSUE THREAD

**Issue by omkarghurye1998** [SNGWN/Burp-Suite#8]
**6.1 For Executing Burp in Windows, Double Click on burp.VBS file.**

![image](https://user-images.githubusercontent.com/33342169/148175557-d037020f-a647-4998-8f66-a494bc73b8e3.png)

![image](https://user-images.githubusercontent.com/33342169/148175488-c77314e4-f443-4ecf-aaa4-67a4f66b23eb.png)

**Comment by SNGWN** [comment]
You need to specify the correct Path for .bat file

**Comment by omkarghurye1998** [comment]
1. Here is my folder structure containing all the files : 
![image](https://user-images.githubusercontent.com/33342169/148214411-e1657c7c-2af3-4f41-9b2e-f86bd57cb298.png)

2. Here is the .bat file with the appropriate changes done : 
![image](https://user-images.githubusercontent.com/33342169/148214686-b0c6dfed-b1ec-4c04-8dd0-989f4c61958b.png)

3. Here is the .vbs file saved in desktop : 
![image](https://user-images.githubusercontent.com/33342169/148214834-1b06b60b-fe5f-4de3-bda3-03963bfd9261.png)

Please let me know if I made any error. Thanks in advance =)


> You need to specify the correct Path for .bat file
