### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by quarinteen** [SNGWN/Burp-Suite#9]
OK This is a weird one. running java --illegal-access=permit -Dfile.encoding=utf-8 -javaagent:"C:\Burp\loader.jar" -noverify -jar "C:\Burp\burpsuite_pro_v2021.2.1.jar" I receive this error "Error: Unable to access jarfile C:\Burp\burpsuite_pro_v2021.2.1.jar". Yes all of the files are in C:\Burp. Yes I have JRE and JDK installed. Proper versions according to your article.

**Comment by quarinteen** [comment]
Ahh you did not update your documentation. In the readme it for 10.3 not 2021.2.1"**Download .jar file for Burp Suite Pro from**
		--> https://portswigger.net/burp/releases/download?product=pro&version=2021.10.3&type=Jar" your command is "burpsuite_pro_v2021.2.1.jar

**Comment by eclipsek20** [comment]
What is your java --version ?

**Comment by unknownuser171** [comment]
> What is your java --version ?
I have the same problem with java version "1.8.0_321"

**Comment by unknownuser171** [comment]
> What is your java --version ?

I have the same problem with java version "1.8.0_321"

**Comment by eclipsek20** [comment]
Try using openjdk

**Comment by Darkuser71** [comment]
> Try using the latest version of openjdk

Yep its worked i fixed it with updating openjdk 

> For more information read this : https://portswigger.net/burp/documentation/desktop/getting-started/launch-from-command-line

**Comment by DarkUser71** [comment]
> Try using the latest version of openjdk

Yep its worked i fixed it by updating openjdk

For more info : https://portswigger.net/burp/documentation/desktop/getting-started/launch-from-command-line

**Comment by DarkUser71** [comment]
> Try using the latest version of openjdk

Yep its worked i fixed it by updating openjdk

> For more info : https://portswigger.net/burp/documentation/desktop/getting-started/launch-from-command-line
